### ISSUE TITLE
Find an alternative way to send data in the contact form

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-next#11]
## 📋 Anything to add?
We used netlify forms in the gatsbyjs version, but that does not work anymore with our hosting being on vercel now. We need to find another way - most practical about the netlify forms was that I was able to pipe the message through to our discord.

## ❓ Why is it important?
We want to have a great support page where different ways to contact us are listed!

## 🎉 Subtasks

- [ ] find a way to send form data to a discord webhook
- [ ] hook up the contact form
- [ ] make new webhook in #support-internal

## 🔗 Work doc - inspirational links
I found these interesting:
- https://dev.to/cyber28/how-i-made-google-forms-automatically-post-submissions-in-our-discord-server-3fh0
- https://www.npmjs.com/package/webhook-discord
- we could also use segment for this

**Comment by mateodaza** [comment]
relates to #30 and #49
