### ISSUE TITLE
Integrate Profile verification for Project owners (Identity)

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-next#27]
## 📋 Anything to add?

- As a project owner, I want to be able to verify my identity and display badges on my profile for my twitter, github, and/or email.
    - When completing a profile, users have the option to connect and verify their Email, Twitter, or Github (via 3box)
    - The verification happens on 3Box... when a user verifies their email, twitter, and/or Github via 3box, we need to detect and save this
    - If a project's creator has verified their twitter, github, or email, a badge for each is displayed on the project's profile that links to their twitter, github, or mailto:email
    - If a user hovers over a twitter, github, or email badge they can see the project's handle or email address in a tooltip as well as a verified icon
    
## ⏰ Urgency/Deadline/Blockers?
This is now part of the GIVBack implementation.

## ❓ Why is it important?

Currently, nowhere in the app we validate the project owner. It appears now the projects are anon, except for the project name a donor doesn't know or can learn more about who's behind the project. We believe this is critical information and many donors will be turned away from donating if project owners are not verified or validated in some way.

Suggestion:
Make user complete their profile (after registering and creating a project) by adding a picture, full name and social media profiles (FB, TW, IN, Github) if they have them, mobile phone number maybe?
Additionally, give user the option to complete their profile with 3Box.

Allow user to sign up ask user to complete the profile in order to be able to Publish a project 
If the user did not complete the profile and creates a project that project is is in a "Pending" state until the user has completed their profile. 

## 🎉 Subtasks

- [x] Discuss further and decide on the user flow and approach
- [ ] Redesign missing UI (if/where needed)
- [ ] Internal testing
- [ ] FE dev implementation

## 🤼‍ Reviewer

@markoprljic @mateodaza @geleeroyale @willyogo
