### ISSUE TITLE
As a Giver, I want to know which projects are eligible for GIVBacks

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-next#47]
## 📋 Anything to add?

- A **GIVBack Badge** is displayed on Verified project's cards and profiles
- If a user hovers over a GIVBack Badge, they see a tooltip, "Givers to this project are eligible to receive up to 75% of their donation back in GIV tokens. _Learn more about GIVBacks_."
- It would be really nice to make sure people know that there is a % of the GIV that they get is claimable and a % that is Locked... we don't want to have them feel like we are tricking them...

## 🎉 Subtasks

- [x] Design GIVBack badge or similar label to be displayed on each project
- [ ] Add Tooltip on hover
- [ ] Create a new page for GIVBack and GIV tokens that explains everything in detail
- [ ] Create a medium blog post explaining how GIVBacks work

**Comment by willyogo** [comment]
AC:
1. If a project's verification status is true, the GIVbacks badges are displayed on their card, profile, and donation page (designs are in progress in [issue #48](https://github.com/giveth/giveth-next/issues/48))
2. The GIVbacks badges are not displayed until the GIV token is launched, and can be easily released as soon as we're ready
