### ISSUE TITLE
Config rate limit on nginx configuration of sensitive services

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-next#613]
## 📋 Anything to add?
Nginx rate limit is an important tool for preventing simple DDoS attacks, as one occurred for trace.giveth.io endpoint.

## ❓ Why is it important?
Our services can be out of service.

## 🎉 Subtasks

- [ ] impact-graph main
- [x] impact-graph stage
- [x] trace.giveth.io (preview service)
- [x] develop.giveth.io (preview service)
- [x] featehrs develop
- [x] feathers beta
- [ ] feathers bridge monitor beta
- [ ] feathers bridge monitor develop
- [x] dapp mailer 

## 🤼‍ Reviewer

@aminlatifi

**Comment by geleeroyale** [comment]
Thanks Amin! I can put it on the servers - can you post the snippet you used for posterity as well?

**Comment by aminlatifi** [comment]
> Thanks Amin! I can put it on the servers - can you post the snippet you used for posterity as well?

@geleeroyale  I used the nginx rate limit and it's configured for feathers and trace preview services. But please check them again.

**Comment by MoeNick** [comment]
@geleeroyale if you have any blocker pls let me know

**Comment by geleeroyale** [comment]
We such a confusing array of feathers services 😅 

I updated these: 

serve.giveth.io
dappmailer.giveth.io
feathers.giveth.io
feathers-alpha.giveth.io
feathers.beta.giveth.io
feathers.bridge.beta.giveth.io
feathers.develop.giveth.io
feathers.bridge.develop.giveth.io
feathers.bridge.release.giveth.io
feathers.mainnet.giveth.io
feathers.release.giveth.io

- others were updated by @mohammadranjbarz and @aminlatifi
- I did update the staging deployment `serve.giveth.io` so we can test the settings, will put them on `mainnet.serve.giveth.io` in next maintenance window

**Comment by MoeNick** [comment]
Should  I close this @geleeroyale ?
I think I'm not able to test all the required stuff is met or not.

**Comment by geleeroyale** [comment]
Yes - this issue can be closed 😇
