### ISSUE TITLE
Adding "Donate" button in the project view 

### ISSUE THREAD

**Issue by Shelpin** [Giveth/giveth-next#682]
## 📋 Anything to add?

A big donate button in the project view after clicking " learn more". 

<img width="689" alt="image" src="https://user-images.githubusercontent.com/21328788/157998926-75b006e3-ea19-4282-8547-944c4a194239.png">

Also when entering the donations view there is no button to donate from that view, so the only "Donate", aka the golden button, is the one shown in the general projects view, when the potential GIVer is seeing just the short descriptions of a bunch of projects. So it might be included in this box and remain there

<img width="692" alt="image" src="https://user-images.githubusercontent.com/21328788/157998935-810c5dd5-150e-43cd-8251-7088fb2d529f.png">

## ⏰ Urgency/Deadline/Blockers?

Not really urgent, in fact I suspect there might be a reason I am not aware of for not having the donate button in those two places now

## ❓ Why is it important?

It avoids two clicks. If I want to dive deeper in a project to read its description and decide to donate I have to go back to the projects view and then click on "Donate". Something might catch my attention in between those two clicks and a donation is flying away 😢

## 🎉 Subtasks

- [ ] Assessing from a UI / design perspective the best way to include it. 
- [ ] Include it in the front-end
- [ ] Track the impact by comparing amount of donations vs page hits coming from the donate button in the general projects view and in the project detailed view / donations view of each project.  

## 🤼‍ Reviewer

@Noideatbh :)))

**Comment by Shelpin** [comment]
Feel dumb rn , @WhyldWanderer already explained me that if I am logged with the profile I created a project with, I do not see the donate button but the edit button. However I see the edit button in every project, not only in the one I created. 

And if I try to hit the edit button it asks me to connect my wallet, and hitting the metamask option takes me back to the connect wallet screen in an endless loop. 

**How to reproduce:**

- Log in with a profile that has created a project

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/21328788/158499118-bc49a3dd-06d5-46d5-a46a-95807d60ec36.png">

- Enter in the learn more section of any other project 

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/21328788/158499154-4f1c66ed-c09a-4533-b887-14c4c19d670d.png">


- Hit edit button 
- Sign.in with ethereum 
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/21328788/158499197-7d878e3c-cf40-4677-b5bf-1bc0c986dac2.png">

- Click Metamask

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/21328788/158499220-e7d2294d-9869-42a7-ae52-a85563efb768.png">

- Takes Back to sign-in with Ethereum 

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/21328788/158499242-dfb99156-c944-4ad1-9834-4a83f3b9f047.png">

Rinse and repeat... :))

**Comment by MoeNick** [comment]
When you click on Metamask, I think its a sign msg, waiting fir you to approve in your wallet? Correct m if its not.

**Comment by MoeNick** [comment]
Oh @ShelpinI think I found the bug. THANK YOU.

**Comment by Shelpin** [comment]
Nothing to thank!! it seemed so weird to me not seeing the donate button, but now it is clear and if it served to catch a little bug, so happy to put half a gwei for an awesome v2!!
